name = "serpentluaserver"
main = "src/index.js"
compatibility_date = "2026-05-03"

[[d1_databases]]
binding = "DB"
database_name = "plugin_index"
database_id = "b0df99a7-8061-4d38-a850-6e6843620951"
migrations_dir = "sql/migrations"